export * from "./orders-mockup";
export * from "./settings-mockup";
export * from "./receipts-mockup";
export * from "./menu-mockup";
export * from "./categories-mockup";
export * from "./transactions-mockup";
export * from "./analytics-mockup";
export * from "./audit-logs-mockup";
export * from "./fallback";
