/**
 * Mockup data for orders management
 * This file contains sample order data for development and testing
 */

export const mockOrders = [
  {
    id: "ord_001",
    orderNumber: "ORD-2024-001",
    customerName: "John Smith",
    mobileNumber: "+1-555-0123",
    status: "completed",
    deliveryType: "dine-in",
    paymentMethod: "card",
    isPaid: true,
    subtotal: 45.5,
    total: 52.33,
    discount: 5.0,
    serviceCharge: 2.0,
    tip: 4.83,
    tax: [
      {
        id: "tax_001",
        name: "Sales Tax",
        rate: 8.5,
        type: "percentage",
        amount: 3.87,
      },
    ],
    items: [
      {
        menuItem: "menu_001",
        name: "Grilled Chicken Sandwich",
        quantity: 2,
        price: 12.99,
        discount: 0,
        prepTime: 15,
        specialInstructions: "No mayo, extra lettuce",
      },
      {
        menuItem: "menu_002",
        name: "Caesar Salad",
        quantity: 1,
        price: 8.99,
        discount: 0,
        prepTime: 10,
        specialInstructions: "",
      },
      {
        menuItem: "menu_003",
        name: "French Fries",
        quantity: 1,
        price: 4.99,
        discount: 0,
        prepTime: 8,
        specialInstructions: "",
      },
      {
        menuItem: "menu_004",
        name: "Coca Cola",
        quantity: 2,
        price: 2.99,
        discount: 0,
        prepTime: 2,
        specialInstructions: "",
      },
    ],
    servedBy: "user_001",
    notes: "Customer requested extra napkins",
    createdAt: "2024-01-15T14:30:00Z",
    updatedAt: "2024-01-15T15:15:00Z",
  },
  {
    id: "ord_002",
    orderNumber: "ORD-2024-002",
    customerName: "Sarah Johnson",
    mobileNumber: "+1-555-0456",
    status: "preparing",
    deliveryType: "takeout",
    paymentMethod: "cash",
    isPaid: true,
    subtotal: 28.75,
    total: 31.19,
    discount: 0,
    serviceCharge: 0,
    tip: 0,
    tax: [
      {
        id: "tax_001",
        name: "Sales Tax",
        rate: 8.5,
        type: "percentage",
        amount: 2.44,
      },
    ],
    items: [
      {
        menuItem: "menu_005",
        name: "Margherita Pizza",
        quantity: 1,
        price: 16.99,
        discount: 0,
        prepTime: 20,
        specialInstructions: "Extra cheese",
      },
      {
        menuItem: "menu_006",
        name: "Garlic Bread",
        quantity: 1,
        price: 6.99,
        discount: 0,
        prepTime: 8,
        specialInstructions: "",
      },
      {
        menuItem: "menu_007",
        name: "House Salad",
        quantity: 1,
        price: 4.77,
        discount: 0,
        prepTime: 5,
        specialInstructions: "Dressing on the side",
      },
    ],
    servedBy: "user_002",
    notes: "Ready for pickup in 20 minutes",
    createdAt: "2024-01-15T16:45:00Z",
    updatedAt: "2024-01-15T16:50:00Z",
  },
  {
    id: "ord_003",
    orderNumber: "ORD-2024-003",
    customerName: "Mike Wilson",
    mobileNumber: "+1-555-0789",
    status: "pending",
    deliveryType: "dine-in",
    paymentMethod: "card",
    isPaid: false,
    subtotal: 67.25,
    total: 75.89,
    discount: 10.0,
    promoDiscount: 5.0,
    serviceCharge: 3.5,
    tip: 0,
    tax: [
      {
        id: "tax_001",
        name: "Sales Tax",
        rate: 8.5,
        type: "percentage",
        amount: 5.14,
      },
    ],
    items: [
      {
        menuItem: "menu_008",
        name: "Ribeye Steak",
        quantity: 1,
        price: 32.99,
        discount: 0,
        prepTime: 25,
        specialInstructions: "Medium rare",
      },
      {
        menuItem: "menu_009",
        name: "Mashed Potatoes",
        quantity: 1,
        price: 6.99,
        discount: 0,
        prepTime: 10,
        specialInstructions: "",
      },
      {
        menuItem: "menu_010",
        name: "Grilled Asparagus",
        quantity: 1,
        price: 8.99,
        discount: 0,
        prepTime: 8,
        specialInstructions: "",
      },
      {
        menuItem: "menu_011",
        name: "Red Wine",
        quantity: 2,
        price: 12.99,
        discount: 0,
        prepTime: 2,
        specialInstructions: "",
      },
    ],
    servedBy: "user_003",
    notes: "Anniversary dinner - complimentary dessert",
    createdAt: "2024-01-15T18:20:00Z",
    updatedAt: "2024-01-15T18:20:00Z",
  },
  {
    id: "ord_004",
    orderNumber: "ORD-2024-004",
    customerName: "Emily Davis",
    mobileNumber: "+1-555-0321",
    status: "delivered",
    deliveryType: "delivery",
    paymentMethod: "card",
    isPaid: true,
    subtotal: 35.5,
    total: 42.15,
    discount: 0,
    serviceCharge: 0,
    tip: 5.0,
    deliveryInfo: {
      address: "123 Main St, Apt 4B, City, State 12345",
      deliveryCharge: 3.5,
      estimatedDeliveryTime: "2024-01-15T20:30:00Z",
      deliveryStatus: "delivered",
      deliveryPartner: "DoorDash",
    },
    tax: [
      {
        id: "tax_001",
        name: "Sales Tax",
        rate: 8.5,
        type: "percentage",
        amount: 3.02,
      },
    ],
    items: [
      {
        menuItem: "menu_012",
        name: "Chicken Pad Thai",
        quantity: 1,
        price: 14.99,
        discount: 0,
        prepTime: 18,
        specialInstructions: "Medium spice",
      },
      {
        menuItem: "menu_013",
        name: "Spring Rolls",
        quantity: 1,
        price: 7.99,
        discount: 0,
        prepTime: 12,
        specialInstructions: "",
      },
      {
        menuItem: "menu_014",
        name: "Thai Iced Tea",
        quantity: 1,
        price: 4.99,
        discount: 0,
        prepTime: 3,
        specialInstructions: "",
      },
      {
        menuItem: "menu_015",
        name: "Mango Sticky Rice",
        quantity: 1,
        price: 7.53,
        discount: 0,
        prepTime: 10,
        specialInstructions: "",
      },
    ],
    servedBy: "user_004",
    notes: "Leave at door if no answer",
    createdAt: "2024-01-15T19:45:00Z",
    updatedAt: "2024-01-15T20:35:00Z",
  },
  {
    id: "ord_005",
    orderNumber: "ORD-2024-005",
    customerName: "David Brown",
    mobileNumber: "+1-555-0654",
    status: "cancelled",
    deliveryType: "dine-in",
    paymentMethod: "card",
    isPaid: false,
    subtotal: 22.5,
    total: 24.44,
    discount: 0,
    serviceCharge: 0,
    tip: 0,
    refundStatus: "refunded",
    tax: [
      {
        id: "tax_001",
        name: "Sales Tax",
        rate: 8.5,
        type: "percentage",
        amount: 1.91,
      },
    ],
    items: [
      {
        menuItem: "menu_016",
        name: "Fish and Chips",
        quantity: 1,
        price: 15.99,
        discount: 0,
        prepTime: 20,
        specialInstructions: "",
      },
      {
        menuItem: "menu_017",
        name: "Coleslaw",
        quantity: 1,
        price: 3.99,
        discount: 0,
        prepTime: 5,
        specialInstructions: "",
      },
      {
        menuItem: "menu_018",
        name: "Lemonade",
        quantity: 1,
        price: 2.52,
        discount: 0,
        prepTime: 2,
        specialInstructions: "",
      },
    ],
    servedBy: "user_005",
    notes: "Customer cancelled due to long wait time",
    createdAt: "2024-01-15T17:15:00Z",
    updatedAt: "2024-01-15T17:45:00Z",
  },
];

export const mockOrderStats = {
  totalOrders: 156,
  totalRevenue: 12450.75,
  averageOrderValue: 79.81,
  completedOrders: 142,
  pendingOrders: 8,
  cancelledOrders: 6,
  todayOrders: 23,
  todayRevenue: 1845.5,
};

export const mockOrderStatuses = [
  { value: "pending", label: "Pending", color: "yellow" },
  { value: "confirmed", label: "Confirmed", color: "blue" },
  { value: "preparing", label: "Preparing", color: "orange" },
  { value: "ready", label: "Ready", color: "green" },
  { value: "completed", label: "Completed", color: "green" },
  { value: "cancelled", label: "Cancelled", color: "red" },
  { value: "refunded", label: "Refunded", color: "gray" },
];

export const mockPaymentMethods = [
  { value: "cash", label: "Cash", icon: "💵" },
  { value: "card", label: "Card", icon: "💳" },
  { value: "digital", label: "Digital Wallet", icon: "📱" },
  { value: "check", label: "Check", icon: "📝" },
];

export const mockDeliveryTypes = [
  { value: "dine-in", label: "Dine In", icon: "🍽️" },
  { value: "takeout", label: "Takeout", icon: "🥡" },
  { value: "delivery", label: "Delivery", icon: "🚚" },
  { value: "drive-thru", label: "Drive Thru", icon: "🚗" },
];
