/**
 * Mockup data for receipts management
 * This file contains sample receipt data for development and testing
 */

export const mockReceipts = [
  {
    id: "receipt_001",
    orderId: "ord_001",
    orderNumber: "ORD-2024-001",
    receiptNumber: "RCP-2024-001",
    customerName: "John Smith",
    servedBy: "Sarah Johnson",
    paymentMethod: "card",
    subtotal: 45.5,
    tax: 3.87,
    serviceCharge: 2.0,
    tip: 4.83,
    discount: 5.0,
    total: 52.33,
    items: [
      {
        name: "Grilled Chicken Sandwich",
        quantity: 2,
        unitPrice: 12.99,
        totalPrice: 25.98,
        specialInstructions: "No mayo, extra lettuce",
      },
      {
        name: "Caesar Salad",
        quantity: 1,
        unitPrice: 8.99,
        totalPrice: 8.99,
        specialInstructions: "",
      },
      {
        name: "French Fries",
        quantity: 1,
        unitPrice: 4.99,
        totalPrice: 4.99,
        specialInstructions: "",
      },
      {
        name: "Coca Cola",
        quantity: 2,
        unitPrice: 2.99,
        totalPrice: 5.98,
        specialInstructions: "",
      },
    ],
    taxBreakdown: [
      {
        name: "Sales Tax",
        rate: 8.5,
        amount: 3.87,
      },
    ],
    printedAt: "2024-01-15T15:15:00Z",
    printedBy: "user_001",
    template: "default",
    status: "printed",
  },
  {
    id: "receipt_002",
    orderId: "ord_002",
    orderNumber: "ORD-2024-002",
    receiptNumber: "RCP-2024-002",
    customerName: "Sarah Johnson",
    servedBy: "Mike Wilson",
    paymentMethod: "cash",
    subtotal: 28.75,
    tax: 2.44,
    serviceCharge: 0,
    tip: 0,
    discount: 0,
    total: 31.19,
    items: [
      {
        name: "Margherita Pizza",
        quantity: 1,
        unitPrice: 16.99,
        totalPrice: 16.99,
        specialInstructions: "Extra cheese",
      },
      {
        name: "Garlic Bread",
        quantity: 1,
        unitPrice: 6.99,
        totalPrice: 6.99,
        specialInstructions: "",
      },
      {
        name: "House Salad",
        quantity: 1,
        unitPrice: 4.77,
        totalPrice: 4.77,
        specialInstructions: "Dressing on the side",
      },
    ],
    taxBreakdown: [
      {
        name: "Sales Tax",
        rate: 8.5,
        amount: 2.44,
      },
    ],
    printedAt: "2024-01-15T16:50:00Z",
    printedBy: "user_002",
    template: "minimal",
    status: "printed",
  },
  {
    id: "receipt_003",
    orderId: "ord_003",
    orderNumber: "ORD-2024-003",
    receiptNumber: "RCP-2024-003",
    customerName: "Mike Wilson",
    servedBy: "Emily Davis",
    paymentMethod: "card",
    subtotal: 67.25,
    tax: 5.14,
    serviceCharge: 3.5,
    tip: 0,
    discount: 15.0,
    promoDiscount: 5.0,
    total: 75.89,
    items: [
      {
        name: "Ribeye Steak",
        quantity: 1,
        unitPrice: 32.99,
        totalPrice: 32.99,
        specialInstructions: "Medium rare",
      },
      {
        name: "Mashed Potatoes",
        quantity: 1,
        unitPrice: 6.99,
        totalPrice: 6.99,
        specialInstructions: "",
      },
      {
        name: "Grilled Asparagus",
        quantity: 1,
        unitPrice: 8.99,
        totalPrice: 8.99,
        specialInstructions: "",
      },
      {
        name: "Red Wine",
        quantity: 2,
        unitPrice: 12.99,
        totalPrice: 25.98,
        specialInstructions: "",
      },
    ],
    taxBreakdown: [
      {
        name: "Sales Tax",
        rate: 8.5,
        amount: 5.14,
      },
    ],
    printedAt: null,
    printedBy: null,
    template: "detailed",
    status: "pending",
  },
  {
    id: "receipt_004",
    orderId: "ord_004",
    orderNumber: "ORD-2024-004",
    receiptNumber: "RCP-2024-004",
    customerName: "Emily Davis",
    servedBy: "David Brown",
    paymentMethod: "card",
    subtotal: 35.5,
    tax: 3.02,
    serviceCharge: 0,
    tip: 5.0,
    discount: 0,
    deliveryCharge: 3.5,
    total: 42.15,
    deliveryInfo: {
      address: "123 Main St, Apt 4B, City, State 12345",
      deliveryPartner: "DoorDash",
    },
    items: [
      {
        name: "Chicken Pad Thai",
        quantity: 1,
        unitPrice: 14.99,
        totalPrice: 14.99,
        specialInstructions: "Medium spice",
      },
      {
        name: "Spring Rolls",
        quantity: 1,
        unitPrice: 7.99,
        totalPrice: 7.99,
        specialInstructions: "",
      },
      {
        name: "Thai Iced Tea",
        quantity: 1,
        unitPrice: 4.99,
        totalPrice: 4.99,
        specialInstructions: "",
      },
      {
        name: "Mango Sticky Rice",
        quantity: 1,
        unitPrice: 7.53,
        totalPrice: 7.53,
        specialInstructions: "",
      },
    ],
    taxBreakdown: [
      {
        name: "Sales Tax",
        rate: 8.5,
        amount: 3.02,
      },
    ],
    printedAt: "2024-01-15T20:35:00Z",
    printedBy: "user_004",
    template: "default",
    status: "printed",
  },
  {
    id: "receipt_005",
    orderId: "ord_005",
    orderNumber: "ORD-2024-005",
    receiptNumber: "RCP-2024-005",
    customerName: "David Brown",
    servedBy: "Lisa Anderson",
    paymentMethod: "card",
    subtotal: 22.5,
    tax: 1.91,
    serviceCharge: 0,
    tip: 0,
    discount: 0,
    total: 24.44,
    refundAmount: 24.44,
    refundReason: "Customer cancelled due to long wait time",
    items: [
      {
        name: "Fish and Chips",
        quantity: 1,
        unitPrice: 15.99,
        totalPrice: 15.99,
        specialInstructions: "",
      },
      {
        name: "Coleslaw",
        quantity: 1,
        unitPrice: 3.99,
        totalPrice: 3.99,
        specialInstructions: "",
      },
      {
        name: "Lemonade",
        quantity: 1,
        unitPrice: 2.52,
        totalPrice: 2.52,
        specialInstructions: "",
      },
    ],
    taxBreakdown: [
      {
        name: "Sales Tax",
        rate: 8.5,
        amount: 1.91,
      },
    ],
    printedAt: "2024-01-15T17:45:00Z",
    printedBy: "user_005",
    template: "default",
    status: "refunded",
  },
];

export const mockReceiptStats = {
  totalReceipts: 1247,
  totalPrinted: 1189,
  totalPending: 45,
  totalRefunded: 13,
  todayReceipts: 23,
  todayPrinted: 21,
  averageReceiptValue: 52.33,
  totalReceiptValue: 65245.5,
};

export const mockReceiptTemplates = [
  {
    id: "template_001",
    name: "Default Template",
    description: "Standard receipt template with all details",
    preview: "default-template-preview.png",
    isDefault: true,
  },
  {
    id: "template_002",
    name: "Minimal Template",
    description: "Clean, minimal receipt design",
    preview: "minimal-template-preview.png",
    isDefault: false,
  },
  {
    id: "template_003",
    name: "Detailed Template",
    description: "Comprehensive receipt with extra information",
    preview: "detailed-template-preview.png",
    isDefault: false,
  },
  {
    id: "template_004",
    name: "Custom Template",
    description: "Customizable template for specific needs",
    preview: "custom-template-preview.png",
    isDefault: false,
  },
];

export const mockReceiptStatuses = [
  { value: "pending", label: "Pending Print", color: "yellow" },
  { value: "printed", label: "Printed", color: "green" },
  { value: "failed", label: "Print Failed", color: "red" },
  { value: "refunded", label: "Refunded", color: "gray" },
];

export const mockPrinters = [
  {
    id: "printer_001",
    name: "Kitchen Printer",
    type: "thermal",
    status: "online",
    location: "Kitchen",
    lastUsed: "2024-01-15T20:35:00Z",
  },
  {
    id: "printer_002",
    name: "Bar Printer",
    type: "thermal",
    status: "online",
    location: "Bar",
    lastUsed: "2024-01-15T19:45:00Z",
  },
  {
    id: "printer_003",
    name: "Receipt Printer",
    type: "thermal",
    status: "offline",
    location: "Front Desk",
    lastUsed: "2024-01-15T17:30:00Z",
  },
];
